### ISSUE TITLE
renew the kamtape domain

### ISSUE THREAD

**Issue by ljcool2006** [fukionline/not-government#1]
not at all related to this repo but this is one of my many attempts to get a response from you

**Comment by fuki98** [comment]
I just wanted direct confirmation before I did it because it’s pretty expensive, thanks, I’ll do this soon

**Comment by fuki98** [comment]
However, a problem might be faced, as I wouldnt be left with much money to also pay for the servers, if I don’t get my allowance tomorrow I will, probably have to rely on donations
I’ll let you know the state of the situation later this Friday. Thanks
